### ISSUE TITLE
Display do not shut down after time-out

### ISSUE THREAD

**Issue by iw2ejh** [richonguzman/LoRa_APRS_iGate#104]
I just installed latest version 2024_05_22 with VSCode (should be the same as the 202_05_23 from web interface?), right procedure FW + Filesystem, my HW is a TTGO LoRa32 V2.1     
the use case is solar powered DIGI + WX     (NO WIFI connection)
I noticed that the display, even if you set to shutdown after 30 second never shut down. (same as before)

**Comment by richonguzman** [comment]
test the latest firmware on github as some changes has been made to the partitions and some info may not be saved correctly on your board

Please do all the configurations on Google Chrome

**Comment by iw2ejh** [comment]
done, now it work
thanks
-marino

**Comment by iw2ejh** [comment]
I have to correct my last statement,  the problem is still present
If it connect to wifi, the screen goes blank after the time out
if there is no connection to wifi ( only digipeater) then the screen remain active.
So it seems that the wifi connection is triggering something

**Comment by iw2ejh** [comment]
No, I put 30 seconds

    Il martedì 28 maggio 2024 alle ore 17:27:17 CEST, Ricardo Guzman (Richonguzman) ***@***.***> ha scritto:  
 
 


Did you put the timeout to zero secs?

**Comment by richonguzman** [comment]
But did it receive a packet in this 30 secs?

**Comment by iw2ejh** [comment]
No, without any traffic. 

    Il martedì 28 maggio 2024 alle ore 17:58:12 CEST, Ricardo Guzman (Richonguzman) ***@***.***> ha scritto:  
 
 


But did it receive a packet in this 30 secs?

**Comment by richonguzman** [comment]
The screen turns on after a packet is received...  it no packet is received it will turns off after "timeOut" time
________________________________
De: iw2ejh ***@***.***>
Enviado: martes, 28 de mayo de 2024 13:47
Para: richonguzman/LoRa_APRS_iGate ***@***.***>
Cc: Ricardo Guzman (Richonguzman) ***@***.***>; State change ***@***.***>
Asunto: Re: [richonguzman/LoRa_APRS_iGate] Display do not shut down after time-out (Issue #104)


No, without any traffic.

Il martedì 28 maggio 2024 alle ore 17:58:12 CEST, Ricardo Guzman (Richonguzman) ***@***.***> ha scritto:




But did it receive a packet in this 30 secs?

**Comment by iw2ejh** [comment]
Yes, I know, in my case it stay on forever.  When I did the upgrade this morning, I keep it connected to wifi to check it from the LAN,  and the screen was shuting down after the timeout,    as soon as I disabled the wifi and used it as pure digi + WX, then the screen stay on and never shut down.
I noticed there is a similar issue #84:  Display always on · Issue #84 · richonguzman/LoRa_APRS_iGate

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Display always on · Issue #84 · richonguzman/LoRa_APRS_iGate

With the Heltec V3 card the display always remains on, even if the correct option and seconds are selected in th...
 |

 |

 |




    Il martedì 28 maggio 2024 alle ore 19:54:31 CEST, Ricardo Guzman (Richonguzman) ***@***.***> ha scritto:  
 
 

The screen turns on after a packet is received... it no packet is received it will turns off after "timeOut" time
________________________________
De: iw2ejh ***@***.***>
Enviado: martes, 28 de mayo de 2024 13:47
Para: richonguzman/LoRa_APRS_iGate ***@***.***>
Cc: Ricardo Guzman (Richonguzman) ***@***.***>; State change ***@***.***>
Asunto: Re: [richonguzman/LoRa_APRS_iGate] Display do not shut down after time-out (Issue #104)


No, without any traffic.

Il martedì 28 maggio 2024 alle ore 17:58:12 CEST, Ricardo Guzman (Richonguzman) ***@***.***> ha scritto:




But did it receive a packet in this 30 secs?
