### ISSUE TITLE
Removing WiFi network doesn't work in Web UI

### ISSUE THREAD

**Issue by epam-vkerkhoff** [richonguzman/LoRa_APRS_iGate#107]
Hello, 

I've set up my iGate at home in my room, however on the roof I have added an AP with a different SSID. Both are entered in the config and are shown in the Web UI. 

I would now like to remove the SSID i used for testing. I hit the trashcan icon next to the and then "SAVE"

Expected behaviour: iGate reboots and the SSID is gone
Actual behavior: iGate reboots and the SSID is still there. 
![Screenshot 2024-05-30 at 17 47 54](https://github.com/richonguzman/LoRa_APRS_iGate/assets/143070075/14c6ebd6-2b80-4e99-82e3-0999609365c9)

**Comment by richonguzman** [comment]
are you deleting the first or second of the list?
