### ISSUE TITLE
Support Heltec Wireless Tracker

### ISSUE THREAD

**Issue by saxa66** [richonguzman/LoRa_APRS_iGate#109]
Hello,

i am just trying to flash igate software on a Helttec wireless tracker. It seems to be supported but I am not sure which board to choose using the web installer. 
Is it supported ?

best regards, thanks for the great job you are doing !

**Comment by richonguzman** [comment]
hi

the Heltec Wireless Tracker Board is supported but on the Github code (installing it with VSCODE)

the web installer will be updated as soon as we fix a few things that show some error in installation)


Github code runs good for sure

**Comment by richonguzman** [comment]
webinstaller now has HELTEC WIRELESS TRACKER on web installer
