### ISSUE TITLE
WiFi not connecting if iGate is turned on before WiFi AP

### ISSUE THREAD

**Issue by 1tilen** [richonguzman/LoRa_APRS_iGate#110]
I have my WiFi router and iGate connected to the same power strip. I noticed that if I unplug the power strip and plug it in iGate would not connect to WiFi. After inspecting everything I noticed that this only happens in case when iGate boots up before my router. 

When I give power to my iGate it turns on its AP which is normal behaviour. My WiFi takes around 1 minute more than iGate to turn on. After the WiFi Timeout which I have set to 10 min iGate does not connect to WiFi. 

In case I plug iGate after my WiFi is turned on iGate normally connects to WiFi and works as it is supposed to.

I have also Beta DiGipeater backup mode turned on if it maybe helps you with diagnosis.

Maybe something like this:
iGate turns on, if there is no WiFi turn on AP. 
After the AP timeout check again.

Do you think this could work?

Thanks!
73 de S54B

**Comment by richonguzman** [comment]
there is a solution already in github code (2024.06.04) 

file : /src/LoRa_APRS_iGate.cpp 


line58: uncomment //#define STARTUP_DELAY 5 //min

this will make the igate wait 5 min to try to connect to wifi and wait for the router to have valid internet info

**Comment by 1tilen** [comment]
I turned on the delay ad it fixed my issue.
Thank you,
Tilen
