### ISSUE TITLE
Support for Lilygo 1.6.1

### ISSUE THREAD

**Issue by jclifford73** [richonguzman/LoRa_APRS_iGate#111]
Hi Ricardo.

Is there any chance of this board being supported?    We have quite a few of our early igates using this board and OE5BPA software.  We would like to migrate at least some of them to your code.
Photo attached

73 John GW4BVE

![20240616_161133](https://github.com/richonguzman/LoRa_APRS_iGate/assets/19248032/072a190d-2688-473b-a456-5e19e2a45913)

**Comment by richonguzman** [comment]
John,

this board is the same as Lora32v2.1 so flash it with this name and would work just fine.

**Comment by jclifford73** [comment]
Thanks for the prompt reply Ricardo.
I tried that with 2 different boards and they lock up on the opening screen.
73 John GW4BVE

**Comment by richonguzman** [comment]
> Thanks for the prompt reply Ricardo. I tried that with 2 different boards and they lock up on the opening screen. 73 John GW4BVE

you need to add a lot more info to your claims as I need it to give you a useful answer


meanwhile.. try to flash it with this link with the new webflasher:

https://richonguzman.github.io/lora-igate-web-flasher/installer.html
