### ISSUE TITLE
Configuration Restore not working

### ISSUE THREAD

**Issue by atomino01** [richonguzman/LoRa_APRS_iGate#113]
Hello, today I get the actual update 1.0.3 via webinstaller.
Than I try to restore the configuration from a backup a few days ago.
I loaded the json file, the data appears in the configuration page, 
after pressing the "SAVE" button, the device reboots. 
After reboot the configuration is still empty.

**Comment by richonguzman** [comment]
Hi


Please try writing the configuration instead of loading the json file
