### ISSUE TITLE
Heltec WSL V3 with BME280 sensor is sending "g...t...r...p...P...h.. b...."

### ISSUE THREAD

**Issue by pamidev** [richonguzman/LoRa_APRS_iGate#119]
I'm trying to connect a BME280 sensor to Heltec WSL V3 using pins 3.3V or 5V, GND, no. 41 and no. 42 - instead of telemetry there is "g...t...r...p...P...h.. b....". When I connect the same sensor to the pins on Raspberry Pi 4B, the sensor works fine. Can anyone test the BME280 sensor with this board and can confirm its operation? I don't know if it's a problem with my board or with the firmware. How to check?

**Comment by richonguzman** [comment]
Hi,

if you start the board and have any serial output app running you will see some info in the boot up process

this will show if the boards is not recognized or its a code thing

can you test inverting SDA/SCL pins ?

**Comment by S57PNX** [comment]
Did you use the Blue logo with L in the settings? Aprs.fi will not detect telemetry and display this strange text in the comment instead. Only the stations with Blue logo will be parsed by aprs.fi as weather stations and parsed accordingly.

**Comment by richonguzman** [comment]
> Did you use the Blue logo with L in the settings? Aprs.fi will not detect telemetry and display this strange text in the comment instead. Only the stations with Blue logo will be parsed by aprs.fi as weather stations and parsed accordingly.

if Wx data Tx is enable, it will/should change the logo into Blue + L automatic.

**Comment by pamidev** [comment]
> Hi,
> 
> if you start the board and have any serial output app running you will see some info in the boot up process
> 
> this will show if the boards is not recognized or its a code thing
> 
> can you test inverting SDA/SCL pins ?

I'll check it and give the answer.

**Comment by pamidev** [comment]
I checked. I tried swapping pins 41/42 as SDA/SCL. I also changed the BME280 power supply from 3.3V to 5V. Unfortunately it does not work. Here are my logs:

`ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x29 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x4bc
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a0c
entry 0x403c98d0

Starting Station: SP8MDH-4   Version: 2024.06.28
Initializing LoRa Module
init : LoRa Module    ...     done!

Connecting to WiFi 'LoRaP' ...
..Connected as 192.168.2.203
[  3863][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3871][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3877][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3883][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3889][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3896][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3902][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3908][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3914][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3920][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3926][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3932][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3939][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3945][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3951][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3957][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3963][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3969][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3975][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3982][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  3988][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  3994][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4000][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4006][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4012][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4018][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4024][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4031][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4037][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4043][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4049][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4055][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4061][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4067][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4073][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4080][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4086][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4092][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4098][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4104][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4110][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4117][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4123][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4129][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4135][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4141][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4147][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4153][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4160][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4166][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4172][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4178][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4184][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4190][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4196][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4203][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4209][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4215][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4221][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4227][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4233][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4239][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4246][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4252][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4258][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4264][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4270][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4276][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4282][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4289][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4295][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4301][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4307][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4313][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4319][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4325][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4331][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4338][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4344][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4350][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4356][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4362][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4368][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4375][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4381][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4387][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4393][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4399][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4405][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4411][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4417][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4424][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4430][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4436][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4442][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4448][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4454][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4460][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4466][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4473][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4479][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4485][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4491][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4497][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4503][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4509][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4516][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4522][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4528][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4534][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4540][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4546][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4552][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4559][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4565][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4571][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4577][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4583][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4589][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4595][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4601][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4608][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4614][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4620][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4626][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4632][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4638][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4644][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4650][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4657][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4663][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4669][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4675][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4681][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4687][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4693][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4700][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4706][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4712][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4718][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4724][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4730][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4736][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4743][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4749][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4755][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4761][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4767][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4774][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4780][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4786][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4792][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4798][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4804][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4810][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4817][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4823][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4829][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4835][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4841][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4847][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4853][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4859][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4866][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4872][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4878][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4884][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4890][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4896][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4903][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4909][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4915][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4921][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4927][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4933][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4939][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4945][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4952][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4958][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4964][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4970][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4976][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4982][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  4989][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  4995][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5001][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5007][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5013][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5019][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5025][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5031][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5038][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5044][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5050][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5056][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5062][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5068][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5074][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5080][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5087][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5093][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5099][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5105][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5111][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5117][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5123][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5130][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5136][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5142][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5148][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5154][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5160][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5166][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5173][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5179][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5185][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5191][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5197][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5203][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5209][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5215][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5222][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5228][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5234][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5240][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5246][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5252][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5258][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5264][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5271][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5277][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5283][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5289][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5295][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5301][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5307][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5314][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5320][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5326][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5332][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5338][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5344][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5350][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5357][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5363][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5369][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5375][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5381][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5387][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5393][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
[  5399][E][Wire.cpp:422] beginTransmission(): could not acquire lock
[  5406][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
Connecting to APRS-IS ...     Connected!
(Server: euro.aprs2.net / Port: 14580)
-- Sending Beacon to APRSIS --
---> LoRa Packet Tx    : SP8MDH-4>APLRG1,WIDE2-2:!L4LlDT4$K_ xG.../...g...t...r...p...P...h..b.....LoRa APRS Digi/iGate 434.855MHz @1k2`

**Comment by S57PNX** [comment]
SP8MDH-4 Is a green icon on aprs.fi. Switch it to blue L and try again - green will not display weather info. 

(Maybe this is not the only problem that you have, but making it a blue icon manually will take away one uncertainty and allow you to focus on real problem. While the firmware should automatically change to blue, do it manually for now.)

**Comment by richonguzman** [comment]
5V BME may be not a good idea as pins on ESP32 need 3.3V reference only

on the other side, does it show any Wx data on screen? or it does not read BME module at all?

**Comment by pamidev** [comment]
> SP8MDH-4 Is a green icon on aprs.fi. Switch it to blue L and try again - green will not display weather info.

Now it is L green, but when testing it was blue, because I switched back. I still have a second LoRa SP8MDH-3 transmitter and there the MeschCom system is sending telemetry data correctly, despite the green icon. See https://aprs.to/

I have a Heltec Wireless Stick Light V3, which does not have a monitor, so I cannot check. The only comment it sends to APRS-IS is:

" g...t...r...p...P...h...b.....LoRa APRS Digi/iGate 434.855MHz @1k2".

**Comment by iw2ejh** [comment]
g...t...r...p...P...h...b..... ==> the fields are empty, so no valid value are sent. May be the BME is not sending data to the esp32 at all are you sure the module is working fine and communication is going on? did you try to power the module with 3.3volts?

**Comment by richonguzman** [comment]
> > SP8MDH-4 Is a green icon on aprs.fi. Switch it to blue L and try again - green will not display weather info.
> 
> Now it is L green, but when testing it was blue, because I switched back. I have a second LoRa Digi/iGate in the MeschCom system as SP8MDH-3 and there is sending telemetry data correctly, despite the green star. See https://aprs.to/station/5247635
> 
> > on the other side, does it show any Wx data on screen? or it does not read BME module at all?
> 
> My BME280 module can be powered by 3.3V or 5V because it has a voltage regulator. I have a Heltec Wireless Stick Light V3, which does not have a screen, so I cannot check. The only comment it sends to APRS-IS is:
> 
> `g...t...r...p...P...h...b.....LoRa APRS Digi/iGate 434.855MHz @1k2`
> 
> Maybe it's a problem with powering the BME280 module from Heltec WSL V3. I will try to power it externally (without using Heltec WSL V3) and test it again.

Telemetry and Wx packets are not the same.

on the powering issue, power it with 3.3v from ESP32S3 would be advisable.

**Comment by steffenspies** [comment]
I also use the Heltec WSL V3 and BME280 and see the same behaviour - exactly the same output, while the same module with a T-Beam works fine. 

Something I haven’t checked yet, because I‘m not home, is bus termination. The T-beam has a display on the same bus, the WSL is BME only. 

I thoughts?

Steffen, DL1SX

**Comment by richonguzman** [comment]
lets start again:

how are you connecting the I2C board? which pins?

**Comment by steffenspies** [comment]
Board: Heltec Wireless Stick Light V3
BME280 connected to Pin 41(SDA) and Pin 42(SCL), powered with 3V3. 

BME280 Board is this one
![image](https://github.com/user-attachments/assets/275f0e0e-c4f7-4e5b-985b-4174cdc9e52c)

When switching "Activate Wx Telemetry" on, the serial monitor shows the exact same output as shown in the message above.

**Comment by richonguzman** [comment]
you are doing exactly as expected and should have good data with it. Is the board BME good?

**Comment by steffenspies** [comment]
It is.
I tried two and put the first one on a T-Beam where it works great. 

The only thing I can think of is that the I2C termination is missing/wrong. 

On the T-Beam is a display also connected to the same I2C bus while on the WSL V3 only the BME280 is connected to.

**Comment by richonguzman** [comment]
found the problem! had a missing wire.begin for this board!

please check it (just uploaded)

**Comment by steffenspies** [comment]
I had to add adafruit Si7021 Library now, but get this error later on

**Comment by richonguzman** [comment]
I added a process to find the board.... I cant test it locally as I have not the board here free

but it should find the bme board now without any issues

**Comment by steffenspies** [comment]
I've made a fresh pull and this time it compiled fine.
I get this on the serial terminal:
`BME/BMP/Si7021 sensor Active in config but not found! Check Wiring`
This is now looking promissing and the error messages from above are gone.
Will check this when being back home and will come back.

First of all thank you for the fix, the project and your support in general.

73, Steffen DL1SX

**Comment by steffenspies** [comment]
Ok, back at home, I did connect a Logic Analyzer to the I2C bus.
What I see: you try to find the sensor by scanning the addresses from 0x01 up to 0x76 and that's exactly what's happening.
The "ack" is always false, accept for 0x76 where it is true (which is the BME280 sensor).

I've zero to none experience with I2C so maybe these screenshots might help.
![grafik](https://github.com/user-attachments/assets/cf30025f-db0e-4925-8b86-c4edcb36893e)
![grafik](https://github.com/user-attachments/assets/c758f9c1-4bb8-4739-bcf5-d4d5d71bdb74)

**Comment by richonguzman** [comment]
so the board is found on the pins you connected...  is it still showing any problem?

**Comment by steffenspies** [comment]
Yes, I still get this:
BME/BMP/Si7021 sensor Active in config but not found! Check Wiring

**Comment by steffenspies** [comment]
I did the same on a T-Beam instead of the Wireless Stick Lite where the sensor is found and working.
`BME280 sensor found
BME280 Module init done!`
As you can see it tries the different addresses to find the sensor until 0x76. That's the same as with the WSL. But on the WSL it doesn't start to read the data from the the sensor.

![Screenshot 2024-08-11 054901](https://github.com/us
![Screenshot 2024-08-11 054752](https://github.com/user-attachments/assets/72b3a371-f0e7-48bd-94ba-f90ce2f5b438)
er-attachments/assets/1432bd12-08f9-42e4-bd1d-ee4c68e764ab)

**Comment by steffenspies** [comment]
I don't have deeper coding experiences, but did a change in bme_utils.cpp and added the two HELTEC_WSL_V3 devices.
Now it is working fine!

`BME280 sensor found
BME280 Module init done!`


`    void setup() {
        if (Config.bme.active) {
            getWxModuleAddres();
            if (wxModuleAddress != 0x00) {
                bool wxModuleFound = false;
                if (wxModuleAddress == 0x76 || wxModuleAddress == 0x77) {
                    **#if defined(HELTEC_V3) || defined(HELTEC_WSL_V3) || defined(HELTEC_WSL_V3_DISPLAY)**        <<<--------- added WSL
                    if (bme280.begin(wxModuleAddress, &Wire1)) {
                        Serial.println("BME280 sensor found");
                        wxModuleType = 1;
                        wxModuleFound = true;
                    }
                    #else
                        if (bme280.begin(wxModuleAddress)) {
                            Serial.println("BME280 sensor found");
                            wxModuleType = 1;
                            wxModuleFound = true;
                        }
                        if (!wxModuleFound) {
                            if (bme680.begin(wxModuleAddress)) {
                                Serial.println("BME680 sensor found");
                                wxModuleType = 3;
                                wxModuleFound = true;
                            }
                        }
                    #endif
                    if (!wxModuleFound) {
                        if (bmp280.begin(wxModuleAddress)) {
                            Serial.println("BMP280 sensor found");
                            wxModuleType = 2;
                            wxModuleFound = true;
                        }
                    }
                } else if (wxModuleAddress == 0x40) {
                    if(sensor.begin()) {
                        Serial.println("Si7021 sensor found");
                        wxModuleType = 4;
                        wxModuleFound = true;
                    }
                }                
`

**Comment by richonguzman** [comment]
> void setup() { if (Config.bme.active) { getWxModuleAddres(); if (wxModuleAddress != 0x00) { bool wxModuleFound = false; if (wxModuleAddress == 0x76 || wxModuleAddress == 0x77) { **#if defined(HELTEC_V3) || defined(HELTEC_WSL_V3) || defined(HELTEC_WSL_V3_DISPLAY)** <<<--------- added WSL if (bme280.begin(wxModuleAddress, &Wire1)) { Serial.println("BME280 sensor found"); wxModuleType = 1; wxModuleFound = true; } #else if (bme280.begin(wxModuleAddress)) { Serial.println("BME280 sensor found"); wxModuleType = 1; wxModuleFound = true; } if (!wxModuleFound) { if (bme680.begin(wxModuleAddress)) { Serial.println("BME680 sensor found"); wxModuleType = 3; wxModuleFound = true; } } #endif if (!wxModuleFound) { if (bmp280.begin(wxModuleAddress)) { Serial.println("BMP280 sensor found"); wxModuleType = 2; wxModuleFound = true; } } } else if (wxModuleAddress == 0x40) { if(sensor.begin()) { Serial.println("Si7021 sensor found"); wxModuleType = 4; wxModuleFound = true; } }

@steffenspies can you post a picture of the code you pasted?

it does not clearly say what you have moded to make it work

I'm right to think you pushed it to work as Wide1 ?

**Comment by steffenspies** [comment]
@richonguzman Yes, in bme_utils.cpp you have already made an ifdef for HELTEC_V3  to use Wire1. 
I only added the HELTEC_WSL_V3 and the HELTEC_WSL_V3_DISPLAY to it in Line 61

![grafik](https://github.com/user-attachments/assets/50d00100-9c92-4451-9919-bc81039c774f)

**Comment by richonguzman** [comment]
great, its added and will be in a few hours in new Release ;)
