### ISSUE TITLE
Syslog messages don't show up in Visual Syslog Server nor WinSyslog

### ISSUE THREAD

**Issue by davidebeatrici** [richonguzman/LoRa_APRS_iGate#121]
Using WireShark I noticed unprintable characters and a wrong timestamp:

![](https://github.com/richonguzman/LoRa_APRS_iGate/assets/5897523/08a1e7c3-431c-4821-82bc-908a714c0100)

Possibly related: lora-aprs/LoRa_APRS_iGate#227

**Comment by iw2ejh** [comment]
what you see after CRC-ERROR are the data not correctly decoded by the LoRa Radio, it include any kind of characters as it is not parsed. These data are useful for debuging. If you notice, the station you are receiving is IK2UUJ and the level is -142dBm, very marginal. This CRC-ERROR is due to the location and distance, in other cases if you see the level higher it may be due to disturb or colision.

**Comment by davidebeatrici** [comment]
Alright, that's what I thought.

According to your screenshot you're receiving the messages just fine in Visual Syslog Server. Is there anything that you had to change in the configuration? Perhaps the filters?

**Comment by richonguzman** [comment]
> Alright, that's what I thought.
> 
> According to your screenshot you're receiving the messages just fine in Visual Syslog Server. Is there anything that you had to change in the configuration? Perhaps the filters?

I guess the problem with timestamp is on the syslog server more than on the igate firmware as it just uploads the log but the log does not push time to it. Its the syslog server that saves his own timestamp into the log.

**Comment by richonguzman** [comment]
as far as I've tested and others told me, the timestamp is added on the syslog server side.

not on yours?

**Comment by davidebeatrici** [comment]
Right now I don't see any messages from iGate, but I'm pretty sure the timestamp is indeed added by the Syslog server.

However, appending the timestamp from the firmware's side would be useful as a reference, especially when there's high latency involved.

**Comment by richonguzman** [comment]
> Right now I don't see any messages from iGate, but I'm pretty sure the timestamp is indeed added by the Syslog server.
> 
> However, appending the timestamp from the firmware's side would be useful as a reference, especially when there's high latency involved.

how much latency are you experimenting?

**Comment by davidebeatrici** [comment]
Nothing too extreme, but in certain environments it may be useful to know exactly when an event happens.

It's just a suggestion, not something I actually need.

**Comment by richonguzman** [comment]
will save this idea for later (when I add NTP server time to igate)

meanwhile I'll close it.

**Comment by davidebeatrici** [comment]
Sounds good!
