### ISSUE TITLE
Digipeater name not added to some packet

### ISSUE THREAD

**Issue by iw2ejh** [richonguzman/LoRa_APRS_iGate#126]
I noticed that some time, I got a packet from a digipeater without no trace of it in the data sent:
I expect to see something like >>>> [originator-1] , [digipeater*] / data load
I got  >>>>>  [originator-1] / data load

see attached example where in the first two row it work fine
in the last two row the digipeater name do not appear.
in both case the originator is [IW2EJH-5]   repeater [IW2EJH-13] and gateway [IW2EJH-11]
(I can understand the data is comming from the digipeater also comparing the dBm of the signal )

I'm running :
FW 2024.01.26 on the tracker
FW 2024.05.27 on the digipeater
FW 2024.05.27 on the iGate

![digipeatermissingasterisk](https://github.com/richonguzman/LoRa_APRS_iGate/assets/17383176/2ee3b5c7-db81-4e0f-bd06-441f7a806524)

**Comment by richonguzman** [comment]
do you have more data to compare?

are this only from digirepeater packets? or is this mixing packets from tracker and digirepeated of the same tracker?

**Comment by iw2ejh** [comment]
-Q>{are this only from digirepeater packets? or is this mixing packets from tracker and digirepeated of the same tracker?} 
-A> This is the syslog comming from the iGate [IW2EJH-11] showing fist line, the signal from the tracker, and the second line, the signal from the digipeater, and it is ok.    then a few data recorded, and finally on line 7, again a signal coming from the tracker, and in line 8, the same data repeated by the digipeater and it is not ok
![digipeatermissingasterisk](https://github.com/richonguzman/LoRa_APRS_iGate/assets/17383176/b04e3b8d-4c87-441b-8503-a8de79cda603)

-Q>{do you have more data to compare?}

Attached highlight of the first data  plus new extract of other log:
(second extract explanation)
row1:   data coming from IW1QAF-12 (I cannot receive it directly because i'm in a closed valley) this signal in fact has been digirepeated by IU2BEF-4 as you can notice in the next two row where we can see in row2: direct data from digi IU2BEF-4 and in raw3: data from IW1QAF-12 repeated by IU2EBF-4*

row6: again signal I cannot receive from IW1QAF-12 that in reality is digirepeated by IU2BEF-4
row8: my tracker IW2EJH-5 that in reality is repeated by my digi IW2EJH-13 
row10: APRSdroid IW2EJH-15 connected to tracker that is repeated by my digi IW2EJH-13

What i can notice from these data, is tha if the digipeater get a position signal, this is working normally, and you get the name of the digi with the asterisk ,  if the data are Telemetry, Message or Status, then the Digipeater name  do not appear in the repeated data. 

![digipeater_data](https://github.com/richonguzman/LoRa_APRS_iGate/assets/17383176/3fb9adf0-ed08-4391-b8bb-f81afc13cca1)

**Comment by iw2ejh** [comment]
I do not know what I touched and by mistake marked as closed.....  sorry I do not know how to remove this completed tag

**Comment by richonguzman** [comment]
so you want the "path" and "tocall" also on the status data log to syslog server?

**Comment by iw2ejh** [comment]
No, I was wondering why the  digipeater name do not appear when it is repeating a packet that is not a gps position. I do not know if this is normal or if this is a bug.  If this is normal forgot my comments, you can close.

**Comment by richonguzman** [comment]
the status packet into the syslog was not defined with this data (path and tocall)

but the original lora packet has it for sure

**Comment by iw2ejh** [comment]
ok, if via RF all is correct, then for me you can close the case. :)
