### ISSUE TITLE
Question: unused Pin's

### ISSUE THREAD

**Issue by DOKTORKROSS** [richonguzman/LoRa_APRS_iGate#132]
Are the unused pins the same and the same number of pins in all boards that the firmware supports? Are they based on the same microcontroller? Sorry I don't have this knowledge and haven't had time to check yet.

Can you list which of them are unused or tell me how to check (for example, the definition section in the files in the SRC directory or otherwise)?

**Comment by richonguzman** [comment]
defined pins are in boards_pinout.h , and this are the used ones for each function (radio, gps, oled and more).

as there are to many boards, you should look at the datasheet and info of the brand and product which will provide the required info

**Comment by DOKTORKROSS** [comment]
Thanks - thats all for the moment.
