### ISSUE TITLE
Add support for ANDFLmsg

### ISSUE THREAD

**Issue by sysadminpower2019** [richonguzman/LoRa_APRS_iGate#148]
Hello, 

I just found this really interesting app that allows for digital modes using android and it has a bluetooth audio interface option. It would be really interesting to see if we could use the bluetooth from the lora board to then feed data in and out of the andflmsg app. 

http://www.w1hkj.com/files/AndFlmsg/

**Comment by richonguzman** [comment]
Hi,

what data would you like to see or send/receive with it?

it looks its not straight forward
