### ISSUE TITLE
Callsign does not pass validation.

### ISSUE THREAD

**Issue by Geksogengo** [richonguzman/LoRa_APRS_iGate#149]
My current callsign R1ZAAG is not validating, can this be fixed? Thanks a lot!

**Comment by richonguzman** [comment]
hi 

is this a valid callsign?
as far as I know if callsign length is 6 characters the third position is the number

**Comment by Geksogengo** [comment]
https://www.qrz.com/db/R1ZAAG 
4 category

**Comment by richonguzman** [comment]
I never saw this type of callsign was a valid one

will try to validate it in code

**Comment by Geksogengo** [comment]
![Screenshot_2024-08-05-12-18-08-62_e2d5b3f32b79de1d45acd1fad96fbb0f~3](https://github.com/user-attachments/assets/66aa2c0a-6b72-4be0-a533-a5ee2a1475d9)

**Comment by wb2osz** [comment]
Here is a list of callsign prefixes:

https://www.arrl.org/international-call-sign-series

73,
John WB2OSZ

**Comment by richonguzman** [comment]
@Geksogengo 

please test 2024.08.05 version :

it should have the fix to your callsign

**Comment by Geksogengo** [comment]
![IMG_20240806_154603](https://github.com/user-attachments/assets/eebd1990-1694-4678-bc50-a03de66b3752)
![IMG_20240806_154757](https://github.com/user-attachments/assets/f28cfa79-61c5-4aee-be17-c031daf1fb80)

**Comment by richonguzman** [comment]
You need to test the new version of github (not web installer)
Web installer will be updated as soon as this is validated

**Comment by Geksogengo** [comment]
![IMG_20240806_213016](https://github.com/user-attachments/assets/a7affeea-b2fb-4958-a096-4d04152e3497)
![IMG_20240806_213020](https://github.com/user-attachments/assets/68cc8f2f-c2db-4fe2-84a5-1334eff29266)
Thank you, everything works! Many thanks for your project, 73!

**Comment by richonguzman** [comment]
great!

**Comment by richonguzman** [comment]
@Geksogengo remember tu use different ssid in your stations as you have at least 2 stations with ssid = -10

**Comment by Geksogengo** [comment]
> @Geksogengoпомните, что вы должны использовать разные ssid на своих станциях, так как у вас есть как минимум 2 станции с ssid = -10
I just recently discovered this error, it's strange that my colleagues didn't tell me about it earlier. But that will only happen in September, when I'll be home. Thanks!
