### ISSUE TITLE
stationMode position 2

### ISSUE THREAD

**Issue by ct1esj** [richonguzman/LoRa_APRS_iGate#15]
Well, in stationMode position 2, it was supposed to receive rf from the tracker and send it to the euro.aprs server where I am connected, that's what it does. Then it was supposed to receive from the server and send the packets via RF at a frequency of 433 MHz so that I could see them on the tracker, well that's not happening.

Is it like that or did I misunderstand?

**Comment by richonguzman** [comment]
you are right! it should


but it would only send RF packets from igate to tracker if the tracker has sended a valid GPS position and the igate has heard him.

only then the igate could transmit APRS-IS packet from internet to RF and the tracker should receive it.
