### ISSUE TITLE
Add support for Meshtastic-DIY board

### ISSUE THREAD

**Issue by Tapkin12ru** [richonguzman/LoRa_APRS_iGate#152]
Hello!
Can you add support for https://github.com/NanoVHF/Meshtastic-DIY/tree/main/PCB/ESP-32-devkit_EBYTE-E22/Mesh-v1.02-2LCD-FreePins board?
Pinouts for it in attach
![image](https://github.com/user-attachments/assets/a04beacf-372a-4d8b-a648-e578f0985124)
Existing build ESP32_DIY_1W_LoRa in your project has another pinouts and not compatible with our boards... This causes problems with updating the firmware. Every time you have to remove the gate and update it locally with a build assembled with pinout changes.

**Comment by richonguzman** [comment]
please write me the pinout definitions for your board to add it as a valid one

**Comment by Tapkin12ru** [comment]
I attached correct pinouts for my board in 1st message. Please compare them with the esp_diy_1w_lora board_pinouts section in your firmware and you will see the difference

**Comment by Tapkin12ru** [comment]
#define RADIO_SCLK_PIN  5
    #define RADIO_MISO_PIN  19
    #define RADIO_MOSI_PIN  27
    #define RADIO_CS_PIN    18
    #define RADIO_RST_PIN   23
    #define RADIO_DIO1_PIN  33
    #define RADIO_BUSY_PIN  32
    #define RADIO_RXEN      14
    #define RADIO_TXEN      13

**Comment by richonguzman** [comment]
please test now:

ESP32_DIY_1W_LoRa_Mesh_V1_2


environment on new update to validate it and add it later to web-installer

**Comment by Tapkin12ru** [comment]
Works fine!

**Comment by richonguzman** [comment]
awesome, so it will stay ;)
