### ISSUE TITLE
Error when trying to OTA update

### ISSUE THREAD

**Issue by Tapkin12ru** [richonguzman/LoRa_APRS_iGate#160]
Hello.
I tried to update my station on TTGO from version 1.0.4.2 to version 1.0.5.1 via Ota update. 
![Screenshot_2024-08-17-17-50-37-710_com opera browser-edit](https://github.com/user-attachments/assets/fa3f8692-f859-4f76-9cca-10d6e59ca19b)

When sending the file ota_update.bin I received this error. So it is impossible to update the firmware via Ota?
![Screenshot_2024-08-17-18-01-21-452_com opera browser-edit](https://github.com/user-attachments/assets/597a006c-f62e-4270-859d-54e1913d86f6) ![Screenshot_2024-08-17-17-50-20-823_com opera browser-edit](https://github.com/user-attachments/assets/908dbb11-3ce8-4b83-a6c9-a5ece9b580d6)

**Comment by richonguzman** [comment]
hi,

which file did you upload?

**Comment by Tapkin12ru** [comment]
This
![Screenshot_2024-08-17-18-15-18-486_com ghisler android TotalCommander-edit](https://github.com/user-attachments/assets/c19e16cd-6483-4ac5-9197-441cd36986fa)

**Comment by richonguzman** [comment]
I always upload the firmware.bin file

will check what happened... can you flash completely fresh?

**Comment by Tapkin12ru** [comment]
> I always upload the firmware.bin file

Did you mean this file?
![Screenshot_2024-08-17-18-30-20-584_com ghisler android TotalCommander-edit](https://github.com/user-attachments/assets/a06eaeac-3f3c-423d-8796-c63cdb4ea258)


> will check what happened... can you flash completely fresh?

I can't do it today because station installed outside of my QTH.

**Comment by richonguzman** [comment]
yes this... please try it and let me know.

**Comment by Tapkin12ru** [comment]
The same error:
"Upload failed
Could Not Activate The Firmware"

**Comment by richonguzman** [comment]
but if you power it off and then on does it run?

**Comment by Tapkin12ru** [comment]
I also tried to update via OTA for version 1.0.5
There is also an error, but a different one.
![Screenshot_2024-08-17-18-54-54-982_com opera browser-edit](https://github.com/user-attachments/assets/58cf00ed-24c5-4253-aa30-a7b83d8d13b8)

**Comment by Tapkin12ru** [comment]
> but if you power it off and then on does it run?

Just now send command for reboot by UI. Station has rebooted and started without problems. But firmware is old.

**Comment by richonguzman** [comment]
so at reboot works with old firmware as normal, but when trying the new firmware it does not work with OTA??

can you try again a few times to validate that its not a wifi speed or distance problem?

**Comment by Tapkin12ru** [comment]
Now I took an identical TTGO board and flashed it via a web installer with erasing to version 1.0.4.2 and via OTA updated to version 1.0.5.1 without errors. Apparently, something bugged on my remotely installed station when I updated it from version 1.0.2 via OTA to 1.0.4.2. I will have to dismantle it and flash it cleanly to 1.0.5.1
And immediately another question: is it necessary to upload the spiffs.bin file to the board in addition to the firmware during OTA update?

**Comment by richonguzman** [comment]
> Now I took an identical TTGO board and flashed it via a web installer with erasing to version 1.0.4.2 and via OTA updated to version 1.0.5.1 without errors. Apparently, something bugged on my remotely installed station when I updated it from version 1.0.2 via OTA to 1.0.4.2. I will have to dismantle it and flash it cleanly to 1.0.5.1 And immediately another question: is it necessary to upload the spiffs.bin file to the board in addition to the firmware during OTA update?

no need to upload spiffs.bin
