### ISSUE TITLE
Support for LLCC68

### ISSUE THREAD

**Issue by Majakkf** [richonguzman/LoRa_APRS_iGate#163]
Hello,

I have a LoRa RA-01SC module, it is based on LLCC68 and i can't get it to work with LoRa APRS 
Would it be possible to add support for these?

**Comment by richonguzman** [comment]
tracker has this also running

do you want to build a ESP32 DIY igate with LLCC68 ?

(PS: this lora module can only go till SF11 as I've read)

**Comment by Majakkf** [comment]
Yes, I want to build DIY igate with this

**Comment by richonguzman** [comment]
> Yes, I want to build a DIY igate with this

ok, i will try to add this, but wait a week until I have the web installer for the tracker ready 

please insist in one more week ;)

**Comment by Majakkf** [comment]
thanks, I'll wait
have a nice day!

**Comment by Majakkf** [comment]
Hi, when it will be ready? @richonguzman
