### ISSUE TITLE
feature request: system time via ntp

### ISSUE THREAD

**Issue by steffenspies** [richonguzman/LoRa_APRS_iGate#164]
How about updating the system time  via ntp if connected to wifi and not having gps.
Update intervall can be set between once per hour to once per day.

Would be useful for logfiles - but not a neccessary feature.

73 de Steffen / DL1SX

**Comment by richonguzman** [comment]
this is a soon to be shared feature, wait until I have the tracker web installer ready and I'll add this to igate
