### ISSUE TITLE
Heltec Lora  32 V3 Display problem

### ISSUE THREAD

**Issue by pdevlin13** [richonguzman/LoRa_APRS_iGate#171]
Hi Ricardo
If I use the web installer to flash a board, the display on the Heltec Lora  32 V3 works ok.
If I use Visual Studio Code with the latest software/firmware from Github the display does not show. All other functions and serial messages work fine. Just wanted to raise this now to prevent any potential problem carrying through to the next release.

Thanks
Paul.

**Comment by g3cwi** [comment]
I found that too today. I finally got my unit going with the web installer.

**Comment by pdevlin13** [comment]
Hi Ricardo, I did have a go to try and work out what was going on. Strangely it seems to be calling the display class functions. I added some serial text, see below. I have added line numbers to  the text to make it a bit clearer See lines highlighted in yellow.

<img width="988" alt="Screenshot 2024-09-06 153707" src="https://github.com/user-attachments/assets/0b4ef71a-5a6d-4e53-abe5-ad3c69af44f1">

**Comment by pdevlin13** [comment]
> I found that too today. I finally got my unit going with the web installer.

Hi Richard, although the display doesn't work, everything else seems to work fine. I just used APRS.fi to check my digipeater was up and running. 
Paul

**Comment by pdevlin13** [comment]
Found a workaround :-) 
<img width="615" alt="Screenshot 2024-09-06 165200" src="https://github.com/user-attachments/assets/5aa2b030-6db2-403c-9d08-a14157885651">
, After a bit of Googling on HeItec V3,I realised that the board SCL, SDA pins were being used to initialise the OLED. Changed the code below, adding or HETLEC_V3 and also changed pins to OLED_SDA, OLED_SCL instead of BOARD_I2C_SDA, BOARD_I2C_SCL

**Comment by g3cwi** [comment]
If we can turn off the display and the wifi AP after a delay, that should reduce the average current and make battery/solar operation, a lot easier.

**Comment by kecsa** [comment]
Hi,
In the new version (09.02), the display became dark.
I2C initialization was missing in Display.cpp.
After
#ifdef OLED_DISPLAY_HAS_RST_PIN ..........  #endif
I typed:
Wire.begin(OLED_SDA, OLED, SCL);
and that solved the problem.
Csaba

**Comment by richonguzman** [comment]
@pdevlin13 , @kecsa , @S57PNX , @g3cwi please test latest update (MAIN BRANCH) which should correct the issue (versionDate = 2024.09.10)

**Comment by kecsa** [comment]
Hi Ricardo,
I tested the 09.10. version.
It works great without any changes.
Thanks for the update and thanks for the great work.
Csaba.

**Comment by g3cwi** [comment]
Tested. Working, thanks.
