### ISSUE TITLE
Portable iGate: How to use the internal GPS of T-Beam

### ISSUE THREAD

**Issue by oe5reo** [richonguzman/LoRa_APRS_iGate#183]
Hello Ricardo!

As far as I know it is only possible to configure fixed, static coordinates into your iGate software. Is there any chance to use the GPS (e.g. of the T-Beam) and use these coordinates for the iGate.

I am thinking of building a portable iGate that can be used from different locations ...

73 Martin
OE5REO

**Comment by richonguzman** [comment]
I just talked to the Gods of APRS and asked about this feature: we have green light... so I will start doing this in next days ;)

**Comment by oe5reo** [comment]
That's great news ... thank you.

If possible you should consider adding the feature **"position ambiguity"** also:
https://blog.aprs.fi/2011/01/position-ambiguity-support.html

**Comment by richonguzman** [comment]
> That's great news ... thank you.
> 
> If possible you should consider adding the feature **"position ambiguity"** also: https://blog.aprs.fi/2011/01/position-ambiguity-support.html

ok, but why? the iGates already have been doing this without ambiguity. Or I should add ambiguity for trackers too?

**Comment by oe5reo** [comment]
When running an portable iGate you probably wouldn't want to tell "the whole world" where exactly the iGate is located. With fixed coordinates you can choose to alter the last digits a bit so not everyone sees the exact spot of your loaction. I did that with my APRS- and LoRa-iGates at home, they are shown on the map about 30-50m away of the real position:

I would like to use the LoRa iGate in my car when I'm out hiking ... POSITION AMBIGUITY would be a simple and easy way to obscure the exact location of my car/iGate a bit.

**Comment by richonguzman** [comment]
> When running a portable iGate you probably wouldn't want to tell "the whole world" where exactly the iGate is located. With fixed coordinates you can choose to alter the last digits a bit so not everyone sees the exact spot of your loaction. I did that with my APRS- and LoRa-iGates at home, they are shown on the map about 30-50m away of the real position:
> 
> I would like to use the LoRa iGate in my car when I'm out hiking ... POSITION AMBIGUITY would be a simple and easy way to obscure the exact location of my car/iGate a bit.

so for igate is ok ambiguity but for tracker not. (I'm not trying to make fun of this , but just to be clear about what the request is)

**Comment by oe5reo** [comment]
For me personally it is only important for iGates (when using the internal GPS). Not for trackers ...

But there are probably other users who would like to see that option on the trackers as well!?

**Comment by richonguzman** [comment]
i was thinking about this too.... will check how to add this ambiguity as it a clever request ;)

**Comment by oe5reo** [comment]
Hi Ricardo,

just tested and it works ... but there is a slight difference between your approach and the one that can be configured in DireWolf and APRS devices like the Kenwood TM-D710.

It seems that you take the last two digits of the latitude and longitude and round them whereas in DireWolf and with Kenwood the operator can choose how many digits should not be transmitted (e.g.: Kenwood TM-D710 manual):
![kenwood_manual](https://github.com/user-attachments/assets/c342989b-54fe-4eb8-8037-5570e2b8488c)

I have configured a 1-digit ambiguity in my APRS iGate running DireWolf ... a pink rectangle on the map view appears if i hoover the mouse over it ... with every new beacon the symbol moves a bit within that rectangle:
![igate_aprs_01](https://github.com/user-attachments/assets/0e22187b-a8f0-4a46-bfef-2569ac3a4f11)
![igate_aprs_02](https://github.com/user-attachments/assets/15e2bfa4-ebb4-47cb-970a-9bd60f082bf1)
![igate_aprs_03](https://github.com/user-attachments/assets/d5f53012-f20d-4ce3-98f9-bb68e3a09cf7)

--------

These are screenshots of the LoRa iGate using internal gps:

![igate_lora_01](https://github.com/user-attachments/assets/62931e39-fb1d-45c3-8ff2-0224b39e3dda)
![igate_lora_02](https://github.com/user-attachments/assets/47159613-207b-47d2-aa5d-c5595beccd53)
![igate_lora_03](https://github.com/user-attachments/assets/c715b1f4-c127-4e4d-8257-5e637b344dda)

-------

So it works perfectly how you configured it ... just wanted to let you know that there is a different approach to the subject in other APRS software like DireWolf, ...

For me personally the option with choosing how many digits of the coordinates should not be transmitted (like in DireWolf, ...) is better. Not sure how difficult it is to implement into your software!? Thanks for your quick response ...

73 Martin
OE5REO

**Comment by richonguzman** [comment]
Martin,

as you already (may) know, there are a few ways to send GPS data: no encoded, Mic-E encoded, base91 encoded.

LoRa Tracker/iGate (my version) runs with base91 encoding for shorter packets. The only problem for this is that ambiguity, like you describe (with the box) runs on "no encoded" and Mic-E only.

The position of the stations is set randomly in this "red box" for this ambiguity. The only way I could find to keep on being base91 encoding is to avoid using more than 2 decimals for GPS (this gives ~1.1km ambiguity). Using only 1 decimals gives 11kms ambiguity. No decimals 111kms.

so "for this test" we have a fixed 1.1Km ambiguity but I can add a selectable "error" for next versions.

**Comment by oe5reo** [comment]
Thank you very much for the information .... I heard about Mic-E and base91 but did not know exactly what was the difference. Also did not know that Position Ambiguity is only available for Uncompressed and Mic-E beacons.

So thanks again for adding this feature ... I think an ambiguity of 1.1km is enough, no need to make it selectable for 11km or even 111km. Would be nice to have an ambiguity of 111m, but that's not possible with base91 if i understand your comments correct.

**Comment by richonguzman** [comment]
> Would be nice to have an ambiguity of 111m, but that's not possible with base91 if i understand your comments correct.

it can be done for sure

maybe we could add a variable ambiguity selector for 111mt, 1.1km, 11km

for initial test I guess 1.1km is enough, right?

**Comment by oe5reo** [comment]
That would be great! 1.1km is enough for testing, will do so in the next days ...

**Comment by oe5reo** [comment]
Did a short test ... worked fine but I think that AMBIGUITY with the current settings is more than 1.1km! I made a screenshot:

![Screenshot 2024-10-15 153554](https://github.com/user-attachments/assets/01494db0-7cb7-4ee6-aa9f-6c7ae6acd832)

The difference between the location of my iGate/car and the coordinates of the transmitted beacon was more than 5km. Experienced this two times.

Later I noticed that on the webinterface I could send beacons manually ... so for the next test tomorrow I will not have to wait 15 minutes :-)

**Comment by richonguzman** [comment]
> Did a short test ... worked fine but I think that AMBIGUITY with the current settings is more than 1.1km! I made a screenshot:
> 
> ![Screenshot 2024-10-15 153554](https://private-user-images.githubusercontent.com/97287167/376635737-01494db0-7cb7-4ee6-aa9f-6c7ae6acd832.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDg2NjksIm5iZiI6MTcyOTAwODM2OSwicGF0aCI6Ii85NzI4NzE2Ny8zNzY2MzU3MzctMDE0OTRkYjAtN2NiNy00ZWU2LWFhOWYtNmM3YWU2YWNkODMyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE2MDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzM2QwZmU5ZjU2ODJiZjdiYzk5Y2EwYTVkMGE0MWUxZjUyNGFmNTg2ZWRmZWI4MTQxMWI0MWM5MjBjOWQzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SzjG6YjbKTk_WSbGB3CrMEiKfi5DRLAyw4fDOOTR21c)
> 
> The other dots on the map are my APRS beacons from the car (OE5REO-9). The difference between the location of my iGate/car and the coordinates of the transmitted beacon was more than 5km. Experienced this two times.
> 
> Later I noticed that on the webinterface I can send beacons manually ... so for the next test tomorrow I will not have to wait 15 minutes :-)

manually should not be done (as this is not ment to be a tracker)

are this 2 beacons gps points how far away?

**Comment by oe5reo** [comment]
> manually should not be done (as this is not ment to be a tracker) <

i know ... i did this just for testing purposes and only via APRS-IS (no TX on 433MHz).

> are this 2 beacons gps points how far away? <

i am not quite sure what you mean ... here is the explaination of my screenshot:

when the igate sent out the beacon i was at this position:
![grafik](https://github.com/user-attachments/assets/514b4b18-69b7-4f64-af8e-e85c01aac1da)
but the beacon showed up on the map here:
![grafik](https://github.com/user-attachments/assets/9ef4d8dc-00d6-4925-9f9e-dfc709684ea2)
there is a distance of over 5km between these two points (line of sight) ...

same with second beacon ... i was at this position when the igate sent out the beacon:
![grafik](https://github.com/user-attachments/assets/7452cd03-84cc-4346-bf7b-908e5c17428a)
but the beacon showed up on the map here:
![grafik](https://github.com/user-attachments/assets/033f28e8-8681-425b-bf5b-4769ca7d6f27)
there is a distance of over 4km between these two points (line of sight) ...

that is why I thought that AMBIGUITY is more than 1.1km

**Comment by richonguzman** [comment]
I get it, but can you check the real positions for both of this points?

they should be XX,XX00000 both for latitude and longitude

**Comment by oe5reo** [comment]
will test the igate on friday on my sota activation. i will leave it in the car for a few hours and will take my tracker with me on the hike. afterwards i will report here how it worked ...

**Comment by oe5reo** [comment]
The test of the iGate today was very positive ... the packets of my tracker were received quite well with a small magnet mount antenna on the roof of the car. I placed the iGate in the trunk of my car where GPS reception seems to be very poor, the T-Beam did not get a GPS fix for several hours:

![lora_igate_track](https://github.com/user-attachments/assets/61ec2346-1fcb-4002-81f9-037110ddff21)

![lora_igate_heard](https://github.com/user-attachments/assets/ccfe0133-8801-46f3-844c-ca8196b73a6b)

![lora_igate_rawdata](https://github.com/user-attachments/assets/a1e02234-aa9b-4443-b350-f285e74be321)

Will do further testing ...

73 Martin
OE5REO

**Comment by richonguzman** [comment]
i see to improvements to this:

1) never send beacons with GPS = 0.0 , 0.0 as Lat and Lng.
2) always send the LAST validated GPS beacon (and if gps fix gets lost, still send those values)

what do you think?

**Comment by oe5reo** [comment]
> never send beacons with GPS = 0.0 , 0.0 as Lat and Lng.

it probably makes sense ... although i found it very useful for testing purposes during my hike to see that the igate was still operating

> always send the LAST validated GPS beacon (and if gps fix gets lost, still send those values)

but when the device is turned off and then on again it should not send the last validated GPS position (because igate could have moved ...)

**Comment by richonguzman** [comment]
> > never send beacons with GPS = 0.0 , 0.0 as Lat and Lng.
> 
> it probably makes sense ... although i found it very useful for testing purposes during my hike to see that the igate was still operating
> 
> > always send the LAST validated GPS beacon (and if gps fix gets lost, still send those values)
> 
> but when the device is turned off and then on again it should not send the last validated GPS position (because igate could have moved ...)

by last  validate GPS data I mean the last from boot up (not any saved from another day or before reset/boot up

**Comment by richonguzman** [comment]
GPS added to Release V2.1 ;)
