### ISSUE TITLE
Feature request: Headless iGate (without OLED display) #173

### ISSUE THREAD

**Issue by btor** [richonguzman/LoRa_APRS_iGate#184]
Hi Ricardo,

You asked me to remind you after the tracker web flasher is completed.
See #173 opened on Sep 8

Best regards,
Bela / HB9HEY

**Comment by richonguzman** [comment]
hi ,

please remember me: was it to have the igate board as digi or as igate without the oled screen?
which board was it?

**Comment by btor** [comment]
Hi Ricardo,

Yes, it was the iGate/digi board. (I use the TTGO Lilygo LoRa32 v2.1 / v1.6  boards for iGates.)
Since I and many other users install them in a waterproof enclosure near the antenna on an antenna tower, the OLED display has no purpose.

**Comment by richonguzman** [comment]
DigiEcoMode waas added in Release V2.0.1 which will disable Wifi, wifiAP , screen and leds and even lower CPU speed to use the least amount of current.
