### ISSUE TITLE
TX on wrong frequency

### ISSUE THREAD

**Issue by jsrudolf** [richonguzman/LoRa_APRS_iGate#190]
There are bug in setting tx frequency. When setting the transmitting frequency to 434855000, the module transmits around 432400000.  Receiver working properly. When using 433775000 everything is ok.- my board is ttgo lora v1.6.

**Comment by jsrudolf** [comment]
it was a hardware problem

**Comment by richonguzman** [comment]
> it was a hardware problem

sorry you find out this , but at least the code is good :)
