### ISSUE TITLE
Variant heltec_wireless_tracker_v1.1

### ISSUE THREAD

**Issue by DL4OCE** [richonguzman/LoRa_APRS_iGate#198]
Hi,

the latest release won't work on my Heltec Wireless Tracker 1.1. I'd love to create a new variant for that device, but I don't know how: when comparing the official documentation and compare it to the already supported v1.0, I cannot find any differences.

Doc v1.0:
https://github.com/jhiggason/lorawirelesstracker/blob/main/manual/vertopal_8f318e01667d414e999cf88216ab1739/media/image5.png

Doc v1.1:
https://resource.heltec.cn/download/Wireless_Tracker/Wireless_Tracker%20_1.1.pdf

Can someone help me find out the right modifications, so I can test it with my device and contribute a commit?

BTW, I downgraded to v1.5.0.1, and the display as well as WiFi started working just like normal. I thought that probably I could now use the OTA upgrade to the latest version, but the OTA flashing tool fails with an error message (unable to fetch).

**Comment by richonguzman** [comment]
Hi Arne,


OTA is not available in Tracker firmware


I need more info about "won't work" , please be more specific at what you tried and what does work and what doesn't

**Comment by DL4OCE** [comment]
I've web flashed version Heltec Wireless Tracker / V2.1.2.1 / full erase. Booting the device, the display won't show anything, neither does the WiFi AP initialize.

**Comment by richonguzman** [comment]
> I've web flashed version Heltec Wireless Tracker / V2.1.2.1 / full erase. Booting the device, the display won't show anything, neither does the WiFi AP initialize.

sometimes ESP32S3 boards (as yours) need to push RST button to start  (check this and let me know)

**Comment by DL4OCE** [comment]
I had restarted it either way, by using the RESET button as well as power cycling it. None of these methods worked.

BUT I simply tried to flash an older version which worked and then upgraded to the latest version, which also worked.

Problem solved, no other variant necessary. When I have the time, I'll try the first device, again, to see if there are any differences.

**Comment by richonguzman** [comment]
meanwhile I will close this issue, but if needed we re-open it ;)
