### ISSUE TITLE
Send voltage/Current charge/discharge from the battery in the comment or telemetry

### ISSUE THREAD

**Issue by IZ1HMT** [richonguzman/LoRa_APRS_iGate#2]
Is it possible to have the voltage and the charge/discharge current on the display and also send them as "Comment" or "Telemetry"? It would be very convenient for an igate/digipeater away from the QTH and battery/solar powered

**Comment by iw2ejh** [comment]
Hello,
may I get some info regarding the battery status in the comment? or even better, in the telemetry?
Thanks
Marinoiw2eh

    Il martedì 4 luglio 2023 alle ore 16:04:16 CEST, Ricardo Guzman (Richonguzman) ***@***.***> ha scritto:  
 
 


hi, I have already some test for internal battery monitoring would you like to test it?

contact me through mail for further details

**Comment by richonguzman** [comment]
Hi

The voltage of the battery could be added to the comment with no problem

But should the battery be the "internal" 4,2v connection or another pin if you want to monitor an even higher voltage battery with a voltage divider??

**Comment by richonguzman** [comment]
The current is a little problematic as there is no info on the internal chip to have this , but it could be calculated by comparing two pins voltage with a 1 ohms resistor

**Comment by richonguzman** [comment]
battery info added on comment and also on screen
