### ISSUE TITLE
free band

### ISSUE THREAD

**Issue by fab1an2** [richonguzman/LoRa_APRS_iGate#20]
Lora is free band, meybe add a way to send message without licence sign on lora?

**Comment by richonguzman** [comment]
It's free . APRS is for Ham Ops.

But maybe you want a Lora messenger without going into APRS world, right?

Like meshtastic?

**Comment by SQ2CPA** [comment]
Use Meshtastic instead if you don't have license, use ISM bands. 
APRS is for Ham Ops only and wouldn't open for people without license. Sorry!
