### ISSUE TITLE
igate and digi + wx ?

### ISSUE THREAD

**Issue by lastclass74** [richonguzman/LoRa_APRS_iGate#27]
any way to make it a igate and digi + wx ?

**Comment by lastclass74** [comment]
any way to make it a igate and digi + wx ?

**Comment by richonguzman** [comment]
hi, igate and digi and wx  (with temperature, pressure and humidity) is already working

do you need more Wx data like wind direction , speed and more?

**Comment by richonguzman** [comment]
did you read the wiki on how to add BME280 as this is used and needed to send WX data?

**Comment by lastclass74** [comment]
Yes and bme280 works fine .. im asking for a mode where lora tx/rx (like beacon and digi) works and on the igate on the same time

**Comment by lastclass74** [comment]
soo i updated to newest version and now it works .. thanks 73
