### ISSUE TITLE
Static IP address

### ISSUE THREAD

**Issue by oe5reo** [richonguzman/LoRa_APRS_iGate#29]
Hi,

would be great to be able to choose between DHCP and a static ip address for the LoRa iGate! Thanks for your work, will probably change from OE5BPA to your software soon ...

73 Martin
OE5REO

**Comment by richonguzman** [comment]
Hi , there are two ways to achieve this:

-define static IP 
-define ip on the router to be fixed

The problem with the first solution is that so far with OTA i encountered some problems with fixed static ip from esp32

But will try to get this running soon

**Comment by oe5reo** [comment]
thanks for the quick reply ...
