### ISSUE TITLE
OTA password issue

### ISSUE THREAD

**Issue by iw2ejh** [richonguzman/LoRa_APRS_iGate#37]
With latest version (web interface) 2024-02-25  when I go to page <ip-of-iGate>/update/ for OTA update,  I was asked for a password, but the this was not accepted. 
The password is set in the previous page (web interface). I also tryied with a blank password, but get the same behavior.

**Comment by richonguzman** [comment]
can you delete any character on the OTA part of the configuration Web Page?

**Comment by iw2ejh** [comment]
Yes, I did that too. no username no passord      
then I go on  the OTA page, and I'm asked for a password,  I let all blank and I'm asked again and again for password

**Comment by richonguzman** [comment]
maybe cleaning/deleting the browser cache will help you with it

**Comment by iw2ejh** [comment]
I used a new browser just for that page, but seme behavior

**Comment by richonguzman** [comment]
SAVE the configuration, it will download a .json file

open it in textEditor app to see if a character is saved there as "user"+"password"

PS: which IP are you using for it?

**Comment by iw2ejh** [comment]
from the saved file (backup) : >         "ota":{"username":"","password":""}}
I'm connecting to 192.168.1.230 that is assigned to the iGate in my network

**Comment by richonguzman** [comment]
so the " 192.168.1.230/update " page does not open or asks for password?

**Comment by iw2ejh** [comment]
the page "192.168.1.230/update does not open (blank page) and is asking for a user name and password in a popup. If I close the page using Abort, the page give " HTTP ERROR 401 "
![Screenshot 2024-02-27 164434](https://github.com/richonguzman/LoRa_APRS_iGate/assets/17383176/71ff77e2-0fa3-4130-98c8-eeab28306bf4)

**Comment by iw2ejh** [comment]
![immagine](https://github.com/richonguzman/LoRa_APRS_iGate/assets/17383176/1c483d6c-eee2-4462-9ef9-e3502cc66d41)

**Comment by iw2ejh** [comment]
even if I put some number like Username  1    password   1,    I got the same behavior

**Comment by iw2ejh** [comment]
![immagine](https://github.com/richonguzman/LoRa_APRS_iGate/assets/17383176/8bbe30e4-0357-456d-a860-bbcb5f4bfad8)

![immagine](https://github.com/richonguzman/LoRa_APRS_iGate/assets/17383176/e9a5fb0a-aa88-464b-b4d6-d6ba30fd7491)

![immagine](https://github.com/richonguzman/LoRa_APRS_iGate/assets/17383176/8565a82b-53a8-4439-856b-671c4b6f24c6)


Same behavior

**Comment by iw2ejh** [comment]
I took down the igate and flashed it again (VSC) with the empty conf.json  file and using the webpage to configure everything work now.  
I still have a couple of questions: 
1- Can we still flash the new version using  VisualStudioC with the conf.json filled with data, or should we aways flash it with the conf.json file empty and go through the local hotspot for the first config and then continue config via web interface??
2- It seems to me that if you configure the igate with the BME function active, when it reboot, if the BME is not connected, you get the message in the display, but also you cannot connect to the Igate anymore, until you reconnect the BME sensor.

**Comment by SQ2CPA** [comment]
You can flash using VSC or you can flash using our installer but it is currently experimental. Both ways should work fine without any problems :) 

If we are talking about BME - I will test it after some time when I will modify the code related to it
