### ISSUE TITLE
Web interface -  coding rate configuration issue

### ISSUE THREAD

**Issue by sp9svh** [richonguzman/LoRa_APRS_iGate#40]
Using web interface (btw thank you very much to the authors for this feature) is not possible to chose 4/7 coding rate parameter which is used in Poland. Available  values ​​are only 4 and 5. Leaving the field blank (to keep the existing setting in igate_conf.json) does not allow to save the configuration.

**Comment by SQ2CPA** [comment]
I know, I'm sorry about that (especially for Polish people) there will be update soon that will fix that
![chrome_2VZ5XztPWK](https://github.com/richonguzman/LoRa_APRS_iGate/assets/155308374/8d4eea58-f9d3-47a2-98ed-56cb0016384c)

Please check your email that you put at QRZ page.
