### ISSUE TITLE
OTA upgrade procedure

### ISSUE THREAD

**Issue by iw2ejh** [richonguzman/LoRa_APRS_iGate#46]
I have a question related to OTA iGate upgrade:
in the webgui we can load "Firmware" and "LittleFS/SPIFFS"
if I want to upgrade the iGate I think I need the Firmware.
Can I get it directly from the zip file "ttgo-lora-v21.zip" (in my case) i downloaded from the link https://github.com/richonguzman/LoRa_APRS_iGate/releases/tag/V1.0.1 , extract the file called firmware.bin and uplade it?  then extract the file spiffs.bin and load it too ?  is this the correct procedure for an OTA upgrade?  Thanks

**Comment by ClassAxion** [comment]
Hello. Flashing `firmware.bin` via OTA should work. I'm not sure about `SPIFFS`. In a while we will have dedicated OTA bins in releases packs.

**Comment by SQ2CPA** [comment]
Fixed in https://github.com/richonguzman/LoRa_APRS_iGate/pull/64
For now you have OTA update binary in installer zip, SPIFFS you need to create yourself because you shouldn't flash clean SPIFFS because this will disconnect your device from WiFi
