### ISSUE TITLE
Mode symbols 

### ISSUE THREAD

**Issue by EA2CW** [richonguzman/LoRa_APRS_iGate#5]
Extracto del README.md

1 = RX iGate, black "L" as symbol
2 = Rx + TX iGate, red "L" as symbol, HAM only. RX will be sent to APRS-IS, Messages will be sent via Lora. Same frequency for RX and TX. By using this feature you have comply with the regulations of your country.
3 = Digipeater simplex, green "L" as symbol, HAM only. Received packets containing WIDEx-x in path will be digipeated on the same frequency. By using this feature you have comply with the regulations of your country.

De acuerdo a la última tabla de simbolos, http://www.aprs.org/symbols/symbols-new.txt de 2021, los símbolos no deberian ser?

Modo 1,  R& = Receive only IGate (do not send msgs back to RF)  *Rombo negro con R
Modo 2,  L& - Lora Igate  * Rombo negro con L

73 y gracias por tu trabajo
Mikel EA2CW

**Comment by Mane76** [comment]
Hello Mikel,

the defined symbol for a LoRa iGate from the Austrian "inventors" is the "black rhombus with white L" (L&) with no information about RX or TX. 
For differentiation between RX only and TX we defined the "red rhombus with white L" (La).

BR
Manfred
