### ISSUE TITLE
Radiolib bandwidth

### ISSUE THREAD

**Issue by Szetya** [richonguzman/LoRa_APRS_iGate#53]
https://github.com/richonguzman/LoRa_APRS_iGate/blob/3fda399ecf369080e0a2013a35662a500ba54658/src/lora_utils.cpp#L66
In radiolib the bandwidth in kHz.

**Comment by richonguzman** [comment]
I'm on it ;)

**Comment by Szetya** [comment]
Also use radiolibet for SX1278. One less library, one less math, one less bug. 😉

**Comment by SQ2CPA** [comment]
Yes, this will reduce flash usage so we will definitely do that!

**Comment by richonguzman** [comment]
corrected!
