### ISSUE TITLE
Feature Request:  KISS output

### ISSUE THREAD

**Issue by N1obu** [richonguzman/LoRa_APRS_iGate#55]
Would it be possible to make a configurable option to all the USB interface output and allow input KISS data?

My hope is to allow the node to connect to an APRS client and act as a KISS TNC device and allow the client software do all the work

**Comment by SQ2CPA** [comment]
Hello. In the next update will be TNC KISS server (TCPIP) and Serial KISS so this will work without any problems with APRSIS32, aprsdroid, etc. For now you can go here and test it if you want, release is available: https://github.com/SQ2CPA/LoRa_APRS_iGate

**Comment by richonguzman** [comment]
> Would it be possible to make a configurable option to all the USB interface output and allow input KISS data?
> 
> My hope is to allow the node to connect to an APRS client and act as a KISS TNC device and allow the client software do all the work

please let us know how it went with the tests ;)

**Comment by N1obu** [comment]
I will test in the next few days. Thanks for the info.

**Comment by N1obu** [comment]
I compiled & uploaded the Dev code you provided.

I'm running Xastir and my TBeam attached as a Serial KISS TNC without any problems.

Tracker TBeam is heard by the i-Gate and passes the beacon to IS-APRS and Xastir.

Xastir beacon is displayed on the i-Gate and on  the Tracker.  However,  the Xastir beacon wasn't passed to IS-APRS.

I left it running and will check on it tomorrow to see if local (filtered m/100) traffic is passed from IS-APRS to RF.

**Comment by SQ2CPA** [comment]
Great! Thank you very much for testing
