### ISSUE TITLE
Igate to digipeater mode if wifi fails

### ISSUE THREAD

**Issue by EA2CW** [richonguzman/LoRa_APRS_iGate#6]
Could it be possible to make the igate works on digi-only mode if the internet connection is down? 
This way the station would be active in either cases.
Thank you,
Mikel EA2CW

**Comment by Mane76** [comment]
Hello Mikel,
this feature is already in development, Ricardo and I defined this as "mode 5" which will come soon. 

This will be a combination of Mode 2 (TX iGate) when aprs-is is available and fallback to Mode 3 (Digi on same freq) when aprs-is is not reachable with a comeback to Mode 2 as soon as aprs-is is available again.

This ensures to have maximum availability with minimum usage of frequency.

BR
Manfred

**Comment by richonguzman** [comment]
stationMode:5 is now available ;)
