### ISSUE TITLE
Feature Request: GPS in iGate

### ISSUE THREAD

**Issue by N1obu** [richonguzman/LoRa_APRS_iGate#61]
It would be nice for the iGate to use the GPS instead of a static position.

**Comment by richonguzman** [comment]
I have this on my TODO list for using a special button , if gps available, to get the current GPS position as the current igate/digirepeater GPS position


also im not very convinced of having a continuos moving igate station.

**Comment by N1obu** [comment]
The intent of having the iGate with GPS is to set up a base-camp scenario with or without Internet capability and then deploying the trackers in that local area (almost like a hiker & camp).   This way we don't have to re-upload the 'json' config file with an updated position.

**Comment by DC4FRT** [comment]
i would also assist the request, to have a mobile or portabel i-Gate if you use the iGate only for some hours or days on the same possition. maybe this could be an choosable option then on the webpage (a software button), i would not need an additional HW-Button
73 and all the best Thomas, DC4FRT

**Comment by mytechguyri** [comment]
Even better if it could connect to a GPS via gpsd  I run a single gpsd server that serves gps coordinates to my entire network.

**Comment by richonguzman** [comment]
can you explain me more about this gaps service or process? write me at telegram @richonguzman

> Even better if it could connect to a GPS via gpsd I run a single gpsd server that serves gps coordinates to my entire network.

**Comment by iw2ejh** [comment]
May be using smartphone GPS to communicate the position to the "mobile iGate" could be a solution? using the web interface for this, and having a software switch to memorize the position is we put the iGate in a new fixed position? This will also help in deploying iGates in various locations.

**Comment by richonguzman** [comment]
GPS in iGate is added in Release V2.1
