### ISSUE TITLE
Feature request: add version number to the WebUI

### ISSUE THREAD

**Issue by S57PNX** [richonguzman/LoRa_APRS_iGate#65]
Can you add versionDate somewhere on the WebUI screen? It would help me track at a glance which version of FW I am running on a specific device, it is easy to lose track otherwise.

Thanks in advance.

**Comment by richonguzman** [comment]
this would be a great add ;)

**Comment by SQ2CPA** [comment]
Yes, we will add that in the footer. Build date, software version (defined in code) and variables used in build.

**Comment by SQ2CPA** [comment]
Done in https://github.com/richonguzman/LoRa_APRS_iGate/pull/68
