### ISSUE TITLE
version 2024.04.09 config issue

### ISSUE THREAD

**Issue by iw2ejh** [richonguzman/LoRa_APRS_iGate#72]
Hello,
I updated to latest version "2024.04.09" and noticed a couple of issue in the configuration.
I updated building and loading the firmware using VSC, then loaded the filesystem.
I had to correct from the Access Point some parameters. I noticed the following problems:
- the beacon is duplicated,  _xxxx become _xxxx_xxxx  
- the display never shut down selecting the relative function.
- I also noticed that you cannot select the Digipeater icon if you have a BME connected.
Tnx
iw2ejh

**Comment by richonguzman** [comment]
hi

please download not again :
duplicated comment fixed when Wx is selected

will check about the display

when Wx data is selected, the symbol/icon should be the blue Circle + L, or aprs.fi won't process it as wx data and only as comment

**Comment by SQ2CPA** [comment]
After selecting BME sensor your symbol will be override to `L_` after saving config. That because any other symbol from the list doesn't make sense because your WX data will be inserted as comment and won't be parsed as WX data with any other symbol than `L_`

**Comment by iw2ejh** [comment]
> After selecting BME sensor your symbol will be override to `L_` after saving config. That because any other symbol from the list doesn't make sense because your WX data will be inserted as comment and won't be parsed as WX data with any other symbol than `L_`

Do you mean the blue circle symbol? or the L overlay?  anyway what if we send the digi symbol with the beacon and the blue circle symbol only when the meteo data is sent? is this possible, so we could know what kind of mode the LoRa device is configured for?  Usually we can configure different kind of beacon with APRS devices. Thanks

**Comment by N1obu** [comment]
I had a problem configuring.  I uploaded new image to my TBeam v1.1 and it stayed on the initial screen.  I could not upload config file.  No access-point was available for me to configure.  I had to erase flash and downgrade back to version 2024.03.28.

**Comment by richonguzman** [comment]
You need to try again to upload filesystem or it won't work

**Comment by N1obu** [comment]
I did several times.  I even completely erased the TBeam and also cleaned the build.  When I downgraded and performed the same load procedure, everything worked fine.  I am using a TBeam v1.1 (915Mhz).  You can see my nodes online at aprs.fi. Search for N1OBU-11 (igate) and -12 (tracker).

**Comment by richonguzman** [comment]
how did you erase the T-beam?


a way to erase all is to write igate firmware (firmware and also filesystem) or meshtastic and go back to write Tracker Firmware and filesystem

sometimes when adding new stuff the .json file of the configuration (although having the same name) won't work and needs to be erased from internal memory

**Comment by SQ2CPA** [comment]
Can you check latest release? We have fixed some problems releated to config. 73! Damian SQ2CPA

**Comment by N1obu** [comment]
I tried then new code. Same results. The code loads, the TBeam resets, I load the file-system (config file). The TBeam resets again, but stays on the initial boot screen. I have tried two different TBeams (one 915Mhz and one 433Mhz), same results.

Using the same loading procedure and using software build 2024.03.28. I am able to load my TBeams.

I am using Visual Studio with PlatformIO.

**Comment by richonguzman** [comment]
wait a day for a new way of installing and avoid VSCODE completely ;)

**Comment by N1obu** [comment]
Here is some more troubleshooting info.  I did a fresh build and upload.  I just changed my callsign in the config json file.  I then watched putty to see what the serial output would be..  Here is my output:

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
AXP192 init done!

Starting Station: N1OBU-13   Version: 2024.04.13
Starting LoRa failed!

==============
As stated before.  If I downgrade to _2024.03.28_ build, everything works fine.

**Comment by richonguzman** [comment]
did you change the frequency on the tracker_conf.json from 433 to 915ish ??

**Comment by N1obu** [comment]
Yes. I'm using 915Mhz TBeams. I switched to my 433Mhz and it works.  

However, the 2024.03.28 build works with my 915Mhz TBeams (igate and tracker).

I can't tell which TBeam has what SX chip on it. I tried searching my past orders through Aliexpress, but no technical information is given. 

All I can tell, some have the NEO-6M GPS and some have the NEO-M8N GPS.  All of them are T22_v1.1.

**Comment by S57PNX** [comment]
Can you attach a photo of your T-beam board? At least the frequency band should be written on the LORA chip, on newer generations of the SX chip even the model is written.

**Comment by richonguzman** [comment]
> Yes. I'm using 915Mhz TBeams. I switched to my 433Mhz and it works.
> 
> However, the 2024.03.28 build works with my 915Mhz TBeams (igate and tracker).
> 
> I can't tell which TBeam has what SX chip on it. I tried searching my past orders through Aliexpress, but no technical information is given.
> 
> All I can tell, some have the NEO-6M GPS and some have the NEO-M8N GPS. All of them are T22_v1.1.

I need to validate that you switched the frequency on the igate_conf.json and uploaded over VSCODE.

(as this is the only way right now to use those freqs)

**Comment by N1obu** [comment]
Yes. I changed the frequency in the JSON config file to 915775000. It worked on the 3.28 build. However I used the TBeam with the NEO-6M GPS.

For testing, I used my spare TBeam with the NEO-M8N GPS.

I found out the 915Mhz TBeams with the 6M GPS have the SX1276 chip. 915Mhz TBeams with M8N GPS have the SX1262 chip.

The 433Mhz TBeam with the 6M GPS have the SX1278 chip.

I'm wondering if the reason 915Mhz worked is because the SX1276 and SX1278 chips have the same architecture. And the SX1262 has a different architecture.

Here are the pictures you asked for
![20240418_175814](https://github.com/richonguzman/LoRa_APRS_iGate/assets/100533255/fec56e14-c9f9-42df-bb27-1e79c8705d81)
![20240418_175918](https://github.com/richonguzman/LoRa_APRS_iGate/assets/100533255/5ae2aeff-61f3-4504-8d76-9fa87aa16c12)

**Comment by richonguzman** [comment]
lets start again:

you have a T-beam V1.1 with SX1262 or SX1268 module?  

also, was the chip different because sx1262 is 433 and yours could be sx1268  for 915 ?

**Comment by N1obu** [comment]
I have several TBeams. All are version 1.1, but they have different LoRa chips based on the GPS chip.

SX1276 is 915Mhz (GPS 6M)
SX1262 is 915Mhz (GPS M8N)

SX1278 is 433Mhz (GPS 6M)

Here is my reference:

![Screenshot_20240418_054517_Chrome](https://github.com/richonguzman/LoRa_APRS_iGate/assets/100533255/43f40b83-e593-43ed-8789-f8c7a402f069)
![image](https://github.com/richonguzman/LoRa_APRS_iGate/assets/100533255/cb09fdcd-f73d-45ac-a5c7-e360c0b0fcbb)

**Comment by richonguzman** [comment]
all worked with last firmware? and now only a few work?

**Comment by richonguzman** [comment]
will add 915 for all boards with SX1276 very soon
