### ISSUE TITLE
NEW feature - Traccar (OsmAnd protocol)

### ISSUE THREAD

**Issue by DonJaume** [richonguzman/LoRa_APRS_iGate#85]
Muy buenas, enhorabuena por el proyecto!!

Podría ser interesante incluir la opción de enviar los datos de posición a servidores Traccar, para uso paralelo o incluso para abrir las puertas a otro tipo de usuarios y bandas como la 868.

El protocolo es bastante sencillo, simplemente hace una petición get por http, formateando la dirección con los datos:
https://www.traccar.org/osmand/

Un saludo
______________________________________________________________________________________

Hello, congratulations for the project!!

It could be interesting to include the option of sending position data to Traccar servers, for parallel use or even to open the doors to other types of users and bands such as 868.

The protocol is quite simple, it simply makes a get request over http, formatting the address with the data:
https://www.traccar.org/osmand/

All the best

**Comment by richonguzman** [comment]
Hola, tu manejas el protocolo para escribir lo necesario para que corra?

> Muy buenas, enhorabuena por el proyecto!!
> 
> Podría ser interesante incluir la opción de enviar los datos de posición a servidores Traccar, para uso paralelo o incluso para abrir las puertas a otro tipo de usuarios y bandas como la 868.
> 
> El protocolo es bastante sencillo, simplemente hace una petición get por http, formateando la dirección con los datos: https://www.traccar.org/osmand/
> 
> Un saludo
> 
> Hello, congratulations for the project!!
> 
> It could be interesting to include the option of sending position data to Traccar servers, for parallel use or even to open the doors to other types of users and bands such as 868.
> 
> The protocol is quite simple, it simply makes a get request over http, formatting the address with the data: https://www.traccar.org/osmand/
> 
> All the best

**Comment by DonJaume** [comment]
Gracias por la pronta respuesta,

Puedo intentarlo, soy prácticamente autodidacta (en su día cuando estudié electrónica usábamos asm) de vez en cuando por "hobbie" y a temporadas hago mis juguetes (pic, arduino, esp), pero todo de "andar por casa". 

Hace unos años lo implementé con módulos E32, arduino y esp8266 y gps en plataforma arduino y usando la libreria httpclient (para jugar).

 Nunca usé Platformio, voy a intentar comprenderlo y ver sus librerias, si consigo algo funcional me vuelvo a poner en contacto con usted.
 
 Muchas gracias, y felicidades por este proyecto, cada día veo nuevos radioaficionados usándolo, parece que va camino de ser un estandar. 73

**Comment by DonJaume** [comment]
Si, con las librerias de arduino con el ESP fue muy sencillo, tengo el código completo que usé, pero es un absoluto "espagueti" (todo era experimentación) muy resumido, la parte donde manda los datos a traccar sería algo así:

`
#include <Arduino.h>
#include <WiFi.h>
#include <HTTPClient.h>

string dominio = "http://test.es";
string port = "5055";

//datos obtenidos del tracker?
string ID = "EA6AMI"
string LAT = "39.138680"
string LON = "2.939659"

void SendHttp()
{
     HTTPClient http;
     http.begin(dominio + ":" + port + "/?id=" + ID + "&lat=" + LAT + "&lon=" + LON);
  
     int httpCode = http.GET();
     if(httpCode > 0) {
         // Envio OK
    }
    else {
       // Error
   }
  
  http.end(); 
}
`

Se pueden incluir varios datos mas, como la hora, altura, dirección, satelites..... pero no se exactamente que datos envía el tracker. 

Un saludo.

**Comment by richonguzman** [comment]
Te parece que armemos una versión solo de eso y probamos que tal anda aparte?

Tienes telegram para ir hablando detalles?

**Comment by richonguzman** [comment]
lo dejamos para despues ;)
