### ISSUE TITLE
Feature request:  Bluetooth

### ISSUE THREAD

**Issue by Vitaliy86** [richonguzman/LoRa_APRS_iGate#87]
Add support bluetooth in KISS and TNC2

**Comment by richonguzman** [comment]
hi,

can you explain a little further the use case of this?

**Comment by Vitaliy86** [comment]
In app APRSdroid

**Comment by richonguzman** [comment]
The tracker firmware has it running for a while

Does this not work for you or do you need another different use-case?

**Comment by Vitaliy86** [comment]
thx
