### ISSUE TITLE
APRSdroid kiss tnc connection lost (TNC KISS Server)

### ISSUE THREAD

**Issue by ltenconi** [richonguzman/LoRa_APRS_iGate#91]
When using the TNC Server option with APRSdroid kiss tnc, APRSdroid gets disconnected and tries to reconnect. The TTGO is logging(Syslog) some packets from APRSdroid so the connection seems to be partially working.  
There are no specific details for APRSdroid in the TNC wiki section https://github.com/richonguzman/LoRa_APRS_iGate/wiki/14.-TNC-information, so I might be missing some configuration to make this work.

Excellent work Ricardo!

**Comment by ltenconi** [comment]
Update: Seems to be working by disabling the socket time out option in Aprsdroid.

**Comment by ltenconi** [comment]
I can confirm TX is working with the following APRSdroid settings:

**Connection protocol:** TNC(KISS)
**Connection type:** TCP/IP
**Start up delay:** 300 ms
**Server:** igate_ip_address:8001
**Socket TCP time out: 0 -> DISABLED!**

**Comment by richonguzman** [comment]
great info! will try to add this to a soon to be made TNC wiki
