### ISSUE TITLE
Support for Destination Address Digipeating

### ISSUE THREAD

**Issue by DayleDrinkwater** [richonguzman/LoRa_APRS_iGate#95]
Hello, the T-Echo firmware by cfr34k (https://github.com/cfr34k/t-echo-lora-aprs) encodes the digi path via the destination field.

 For example `APLETK-1` should translate to digipeating the same as `WIDE1-1`, as specified in http://www.aprs.org/doc/APRS101.PDF , page 15, "Generic APRS Digipeater Path"

However this is not followed in this firmware. Please can support be added to allow this type of digipeating. 

Using this format decreases the length of the packet and will help with decoding errors and congestion.

Thanks, 
Dayle M0OUE

**Comment by wb2osz** [comment]
This feature is generally considered to be obsolete.
Discussion here:  https://groups.io/g/APRS/topic/106911039#msg2836 

73,
John WB2OSZ
